name: ios-tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    unit-tests:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - run: cd apps/ios && bundle install && gem uninstall cocoapods --version '>= 1.12.0'
              # cocoapods-patch does not support cocoapods 1.12.0 yet
            - run: cd apps/ios && pod install
            - name: Test
              run: xcodebuild test -workspace apps/ios/GuideDogs.xcworkspace -scheme Soundscape -testPlan UnitTests -destination 'platform=iOS Simulator,name=iPhone 13'
